apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
        version: v1
    spec:
      containers:
        - name: nodejs-app
          image: 914509617440.dkr.ecr.us-east-1.amazonaws.com/workspace/nodejs-demo:v2
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: PORT
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: nodejs-secrets
                  key: API_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nodejs-secrets
                  key: DATABASE_URL
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: nodejs-config
        - name: secrets-volume
          secret:
            secretName: nodejs-secrets

