{
 "title": "App",
 "time": { "from": "2025-01-06T14:12:13.936Z", "to": "2025-01-06T16:45:54.490Z" },
 "panels": [
  {
   "title": "Percentage of Errors (Error Rate %)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"2..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Database Queries",
   "type": "stat",
   "description": "Tracks the total count of database queries since the application started.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(db_query_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Grouped by Method",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by(method) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "rate(db_query_duration_seconds_sum[5m]) / rate(db_query_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by Endpoint 5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db_query_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "rate(db_query_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}